---
- name: "Checks system"
  include: checks.yml

- name: "Install role requeriments"
  include: requeriments.yml

- name: "Install and configure Singularity registry"  
  include: sregistry.yml
  when: (sregistry_is_installed is failed) and (install_sregistry)

- name: "Install and configure Singularity registry CLI"  
  include: sregistry-cli.yml
  when: (sregistry_cli_is_installed is failed) and (install_sregistry_cli)
