
- name: "Clone sregistry-cli git repo - {{ sregistry_cli_branch }}"
  git:
    repo: 'https://github.com/singularityhub/sregistry-cli.git'
    dest: "{{ sregistry_cli_dir }}"
    version: "{{ sregistry_cli_branch }}"

- block:
  - name: "Install sregistry-cli"
    command: python setup.py install
    args:
      chdir: "{{ sregistry_cli_dir }}"
  when: not sregistry_cli_use_docker

- block:
  - name: Build image
    docker_image:
      name: vanessa/sregistry-cli
      build:
        path: "{{ sregistry_cli_dir }}"
      source: build
    when: "ansible_version.full is version_compare('2.8', '>=') "

  - name: Build image
    docker_image:
      name: vanessa/sregistry-cli
      path: "{{ sregistry_cli_dir }}"
    when: "ansible_version.full is version_compare('2.8', '<') "

  - name: Create alias in .bashrc
    lineinfile:
      path: /root/.bashrc
      regexp: '^alias sregistry="docker run '
      line: 'alias sregistry="docker run -i --network=host -e SREGISTRY_CLIENT=registry --privileged vanessa/sregistry-cli"'
  when: sregistry_cli_use_docker 
